### ISSUE TITLE
Method update for Customer is missing

### ISSUE THREAD

**Issue by im-bart** [chartmogul/chartmogul-php#10]
The `ChartMogul\Enrichment\Customer::update` method as described by the documentation is missing.

**Comment by im-bart** [comment]
I see this is defined in UpdateTrait. I'm wondering why it throws a `Call to undefined method` fatal error though.

**Comment by jasonl** [comment]
Hi @im-bart 

Thanks for bringing this to our attention - let me have a look into it, and I'll get back to you.

**Comment by im-bart** [comment]
I see this was actually fixed recently, latest version works excellent. Thanks anyway!
