### ISSUE TITLE
Error: "Undefined constant 'ChartMogul\DEFAULT_MAX_RETRIES'" after upgrading to PHP 8.2 and Symfony 6.3

### ISSUE THREAD

**Issue by h3llr4iser** [chartmogul/chartmogul-php#111]
I'm experiencing an issue after upgrading my project to PHP 8.2 and Symfony 6.3. The error message I'm getting is:

Undefined constant "ChartMogul\DEFAULT_MAX_RETRIES"

I managed to work around the issue by moving the constant inside the Configuration class like this:

```php
<?php

namespace ChartMogul;

/**
 *
 * @codeCoverageIgnore
 */
class Configuration
{

    const DEFAULT_MAX_RETRIES = 20;

    /**
     * @var null|Configuration
     */
    private static $defaultConfiguration = null;

    /**
     * @var string
     */
    private $accountToken = '';
    /**
     * @var string
     */
    private $secretKey = '';
    /**
     * @var int
     * maximum retry attempts
     */
    private $retries = self::DEFAULT_MAX_RETRIES;

    /**
     * Creates new config object from accountToken and secretKey
     * @param string $accountToken
     * @param string $secretKey
     */
    public function __construct($accountToken = '', $secretKey = '', $retries = self::DEFAULT_MAX_RETRIES)
    {
        $this->accountToken = $accountToken;
        $this->secretKey = $secretKey;
        $this->retries = $retries;
    }

```
Related with PR [#112](https://github.com/chartmogul/chartmogul-php/pull/112)

**Comment by kmossco** [comment]
@h3llr4iser sorry for the delay here, I merged your PR but did not release a new version as we were discussing internally what would be the best way to roll out the new pagination changes and whether we would bundle your changes there. We'll release a minor version upgrade with your changes today or tomorrow at the latest.

**Comment by h3llr4iser** [comment]
OK, thank you. No problem, I understand perfectly. I'm not in a rush; for now, I'm using my fork. When you release a new version, I'll update it.

**Comment by kmossco** [comment]
A release was now created for the version `5.1.2`.
