### ISSUE TITLE
Customer->subscriptions() doesn't work

### ISSUE THREAD

**Issue by adyr** [chartmogul/chartmogul-php#25]
$cus = new ChartMogul\Customer([
		    "uuid" => $user->uuid
			]);
		
$subscriptions = $cus->subscriptions();

results in:

PHP Fatal error:  Uncaught exception 'ChartMogul\Exceptions\ChartMogulException' with message 'Subscription request error has occurred. Response:
 <!DOCTYPE html>
<html>
<head>
  <title>We're sorry, but something went wrong (500)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-colo in /home/bpzadmin/public_html/wp-content/mu-plugins/bookpagez-chart-mogul/chart-mogul/vendor/chartmogul/chartmogul-php/src/Http/Client.php on line 222

**Comment by pkopac** [comment]
Hi @adyr, thank you for reporting, I will investigate.

**Comment by pkopac** [comment]
Please try again, we had an outage on the Import API, which caused the HTTP 500 failure. I've checked the library and this should work as expected.
