### ISSUE TITLE
404 error on subscription list

### ISSUE THREAD

**Issue by adyr** [chartmogul/chartmogul-php#26]
The following code trows a 404 if the specified customer doesn't have any subscriptions, if it is just a lead.  

```
$cus = new ChartMogul\Customer([
			"uuid" => $user->cm_uuid
			    ]);
$subscriptions = $cus->subscriptions();
```

**Comment by pkopac** [comment]
Thank you for reporting. We are working on a fix.

**Comment by pkopac** [comment]
@adyr, can you please verify it works now?
It was Import API error (not PHP library error), fix has been just deployed.
Thank you.

**Comment by adyr** [comment]
It works now. Thank you.
