### ISSUE TITLE
Return type DocBlock value

### ISSUE THREAD

**Issue by gjuric** [chartmogul/chartmogul-php#31]
I believe [AbstractResource::all()](https://github.com/chartmogul/chartmogul-php/blob/23e654315955daec84776ea9a8afaeac01313a62/src/Service/AllTrait.php#L16) should return ```self[]```as well. It would help with autocomplete and warnings in IDEs.

**Comment by pkopac** [comment]
Hi @gjuric, thank you for the suggestion. IDK what you mean exactly. Can you submit a PR with your proposed change, please?
