### ISSUE TITLE
ChartMogul\Customer::findByExternalId Doesn't Work

### ISSUE THREAD

**Issue by cabreran** [chartmogul/chartmogul-php#35]
I was able to add customers but unable to List Customers, Search by email or Find by External_Id, nor can I find plans by external_id they just don't work. 

I get a response code 200, but with no result data. Dies silently.

**Comment by Uladzimiro** [comment]
Thanks for reaching out.
After a small investigation, we figured out that the wrong version of PHP was used.
Closing this issue as everything works properly with PHP 5.5.
