### ISSUE TITLE
Static function should not be abstract

### ISSUE THREAD

**Issue by pupitooo** [chartmogul/chartmogul-php#38]
PHP Strict standards: Static function ChartMogul\Resource\EntryTrait::getEntryClass() should not be abstract in /var/www/smartlook/application/vendor/chartmogul/chartmogul-php/src/Resource/EntryTrait.php:12

**Comment by pkopac** [comment]
Hi @pupitooo, thanks for reporting, we'll check it out.

**Comment by hassansin** [comment]
@pupitooo this has been fixed in 1.1.10 and 2.0.1 releases. Please check release notes for details.
