### ISSUE TITLE
Two definitions with same name

### ISSUE THREAD

**Issue by pupitooo** [chartmogul/chartmogul-php#39]
https://github.com/chartmogul/chartmogul-php/blob/325f9a0d57c3da9ed55f4e639be764de351c7e93/src/Metrics.php#L5 
vs
https://github.com/chartmogul/chartmogul-php/blob/325f9a0d57c3da9ed55f4e639be764de351c7e93/src/Metrics.php#L11

**Comment by hassansin** [comment]
@pupitooo this has been fixed in 1.1.10 and 2.0.1 releases. Please check release notes for details.
