### ISSUE TITLE
Version 2.2.0 is breaking 2.1.0

### ISSUE THREAD

**Issue by fkupper** [chartmogul/chartmogul-php#60]
Because of strict return types, version 2.2 is not compatible with 2.1, therefore all projects requiring it as `^2.1` will potentially have problems (I did).

**Comment by pkopac** [comment]
@fkupper thank you for reporting, we'll investigate ASAP.

**Comment by fkupper** [comment]
FYI:

```
Type error: Return value of ChartMogul\Customer::findByExternalId() must be an instance of ChartMogul\Customer or null, bool returned
```
