### ISSUE TITLE
Please don't rely on httpguzzle directly

### ISSUE THREAD

**Issue by pscheit** [chartmogul/chartmogul-php#69]
Since the repo does require to use guzzle 6, it's hard to upgrade.

Better rely on the psr client interface for http clients and let the people plug in guzzle 6 or 7 or symonfy http client

thanks so much
philipp

**Comment by pkopac** [comment]
Thank you for pointing this out. We're releasing this as a major version change here:
https://github.com/chartmogul/chartmogul-php/releases/tag/3.0.0
