### ISSUE TITLE
Laravel 8 not supporting

### ISSUE THREAD

**Issue by png-prakash** [chartmogul/chartmogul-php#71]
- chartmogul/chartmogul-php 2.2.4 requires php-http/client-implementation ^1.0 -> satisfiable by php-http/guzzle6-adapter[dev-master, 2.x-dev, v2.0.1].
    - php-http/guzzle6-adapter v2.0.1 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev].
    - php-http/guzzle6-adapter 2.x-dev requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev].
    - php-http/guzzle6-adapter dev-master requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev].
    - Conclusion: don't install guzzlehttp/guzzle 6.5.x-dev

**Comment by hassansin** [comment]
`chartmogul/chartmogul-php 2.2.4` looks like the previous version where we had a dependency on `php-http/guzzle6-adapter`. Please upgrade to version `3.0.0` where we've removed dependency on abt concrete HTTP client libraries

**Comment by png-prakash** [comment]
Hi
I used
composer require chartmogul/chartmogul-php:^3.0 php-http/guzzle6-adapter:^2.0.1 http-interop/http-factory-guzzle:^1.0

And I got error

Problem 1
    - php-http/guzzle6-adapter 2.x-dev requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - php-http/guzzle6-adapter v2.0.1 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Conclusion: don't install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for php-http/guzzle6-adapter ^2.0.1 -> satisfiable by php-http/guzzle6-adapter[2.x-dev, v2.0.1].

**Comment by hassansin** [comment]
You are specifying two versions of guzzle: 2.0.1 and 6.5.x-dev at the same time. Since you already need guzzle 6 by some other package, don't install guzzle 2.0.1. So try something like following:

```
composer require chartmogul/chartmogul-php:^3.0 http-interop/http-factory-guzzle:^1.0
```

**Comment by png-prakash** [comment]
Hi,

When install
composer require chartmogul/chartmogul-php:^3.0 http-interop/http-factory-guzzle:^1.0

I got error like this

Problem 1
    - Installation request for chartmogul/chartmogul-php ^3.0 -> satisfiable by chartmogul/chartmogul-php[3.0.0].
    - chartmogul/chartmogul-php 3.0.0 requires php-http/client-implementation ^1.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by gjuric** [comment]
You need to install one of the packages that provide `php-http/client-implementation` you can find a list of packages that provide that here: https://packagist.org/providers/php-http/client-implementation
