### ISSUE TITLE
 cURL error 6: getaddrinfo() thread failed to start  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by AidasK** [chartmogul/chartmogul-php#74]
After 100-200 requests to chartmogul php fails with exception " cURL error 6: getaddrinfo() thread failed to start  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)" Retrying same request works as expected, but it fails again after 100-200 requests. 

Sometimes it fails with "Http\Client\Exception\NetworkException  : cURL error 6: Could not resolve host: api.chartmogul.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)" error too.

**Comment by pkopac** [comment]
Hey, @AidasK,

thanks for reporting. Albeit I don't think it's a problem of our library or server. It seems like your environment/local system has some intermittent issues with DNS resolution. Literally it says it can't resolve the hostname to IP address, so it can't even send a request. :shrug:

**Comment by AidasK** [comment]
Actually I have created this problem myself. I have created a new Guzzle client for each request and this client was persisted in the returned resource of Chartmogul, hence connection was also kept open. Because of this I have reached my open files limit and it crashed with a random error.
