### ISSUE TITLE
Replace static api with instance services

### ISSUE THREAD

**Issue by slepic** [chartmogul/chartmogul-php#77]
Currently, it is very easy to call the static methods.
```
$c1 = Customer::findByExternalId($extId1);
$c2 = Customer::findByExternalId($extId2);
```

But since we can inject own http client, it becomes cumbersome to call the static api of this lib.
```
$client = createCustomClient();
$c1 = Customer::findByExternalId($extId1, $client);
$c2 = Customer::findByExternalId($extId2, $client);
```

note: hehe actually looking at the code, `findByExternalId` currently does not even support passing the client as second argument which even makes an inconsistent and partially inaccessible api.

Let me even explain why I believe passing a custom client instance (even if the default is passed) is better and should be the prefered if not the only option. 
See the first snippet, see how the client is never passed to the static methods? When it is not passed it undergoes the entire client building process again and again on every call to the static api, which is of course very ineffective.

Let's see how this can be implemented obeying the single responsibility and dependency inversion principles:
```
$client = createCustomClient();
$customers = new CustomersService($client); // or pass no client and default may be built, but personally i would always inject
$c1 = $customers->findByExternalId($extId1);
$c2 = $customers->findByExternalId($extId2);
```
See how we removed the client argument from all methods that were formerly static and part of a class that should only be responsible for holding a single customer data.

Of course this makes a completley new api and lot has to be refactored in both the lib and its consumers. However there is quite a smooth migration path:

First create the service classes and delegate to the static api while also deprecating the static api:
```
class CustomersService
{
  public function __construct(private ClientInterface $client) {}

  public function findByExternalId(string $externalId): ?Cursomer
  {
     return Customer::findByExternalId($externalId, $this->client);
  }
}

class Customer
{
  /** @deprecated use CustomersService */
  public function findByExternalId(string $externalId, ?ClientInterface $client = null): self
  {
    if ($client === null) {
      trigger_user_error(E_USER_DEPRECATED, '...');
    }

    // previous implementation
  }
}
```
Then it can be released allowing consumers to change their code.
And then you can continue working on moving the logic to the services themselves while keeping the deprecated method but adding user errors

```
class Customer
{
  /** @deprecated use CustomersService */
  public function findByExternalId(string $externalId, ?ClientInterface $client = null): self
  {
    trigger_user_error(E_USER_DEPRECATED, '...');
    return (new CustomersService($client))->findByExternalId($externalId);
  }
}
```
This all can even be done method by method, service by sevice, not at all needed to do it in one go and it will be minor releases all the time.

But when it is all finished, all logic is in services and all data classes delegate to temporary created service instance, then in one go remove all the deprecated methods and release a new major version. As the minor versions were all emitting deprecations and new way to achieve same results was always possible, consumers have had quite a lot of time for transition and the transition itself is quite straight forward.

As a cherry on top, I propose to also remove any nullable constructors parameters in the services and the client and remove http client discovery so that the end code must look minimally like this:

```
$psrHttpClient = psrClient(); // always custom
$config = new Configuration(); // this is the only one that has defaults and only scalars
$client = new Client($config, $psrHttpClient, $psrRequestFactory);
```

for simplification you could keep the client autodiscovery but this should be optional (require-dev in composer) and in a factory class:
```
class ClientFactory
{
  public static function create(
        Configuration $config = null,
        HttpClient $client = null,
        RequestFactoryInterface $requestFactory = null
    ): ClientInterface {
        if (!\class_exists(HttpClientDiscovery::class) || !\class_exists(Psr17FactoryDiscovery::class)) {
          throw new \Exception('Please install optional dependency php-http/discovery or pass you own psr client and request factory instances');
        }
        $config ?: new Configuration();
        $client = $client ?: HttpClientDiscovery::find();
        $requestFactory = $requestFactory ?: Psr17FactoryDiscovery::findRequestFactory();
        return new Client($config, $client, $requestFactory);
    }
}
```

**Comment by pkopac** [comment]
@slepic thank you for the detailed suggestions, we'll look into it next month.

**Comment by slepic** [comment]
thanks, I am also willing to help implementing this...

**Comment by pkopac** [comment]
@slepic that would be great, thank you, feel free to open a PR! If it's backwards-compatible, there should be no issues with merging.

**Comment by slepic** [comment]
Hello, sorry for no response, I eventually decided to roll own a custom implementation for only what I needed rather than contributing to outdated codebase.
