### ISSUE TITLE
Please update README

### ISSUE THREAD

**Issue by raph8888** [chartmogul/chartmogul-php#97]
Instead of 

```
ChartMogul\Configuration::getDefaultConfiguration()->setApiKey('<YOUR_API_KEY>');
```

It should be:

```
ChartMogul\Configuration::getDefaultConfiguration()->setAccountToken('<YOUR_API_KEY>');

ChartMogul\Configuration::getDefaultConfiguration()->setSecretKey('<YOUR_API_KEY>');
```

**Comment by blakemcintyre** [comment]
The version that is listed in the current README matches recent changes that we've made to how our API authenticates requests. We are no longer using the combination of API key and secret key. Instead we are using a single API token. The most recent version of this library has been updated to reflect this. The old style of passing 2 parameters will be removed in the next major release. Until then you can still use them but the secret key value will be ignored.

For more information on this change please see https://dev.chartmogul.com/docs/authentication.

**Comment by marnickmenting** [comment]
You should still update the README to `composer require chartmogul/chartmogul:^5.0` to install the latest version. I got the same error when following the docs like they are now.

**Comment by pkopac** [comment]
@marnickmenting thanks, I'll update it ASAP in #101
